import type { Metadata } from "next";
import { Comfortaa } from "next/font/google";
import "../globals.css";
import Header from "@/components/organisms/Header";

// const nunitoFont = Nunito({
//   subsets: ["cyrillic"],
//   variable: "--font-nunito",
//   weight: ["400", "500", "600", "700", "800", "900"],
// });

const comfortaaFont = Comfortaa({
  subsets: ["cyrillic", "latin"],
  variable: "--font-comfortaa",
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${comfortaaFont.className} antialiased`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
