import { services, stock_categories, stock_images } from "@/generated/prisma";
import { Decimal } from "@/generated/prisma/runtime/library";
import { prisma } from "@/prisma/prisma-clent";

const mockServices: services[] = [
  {
    id: 0,
    service_name: "sweatshot",
    uv_url: "/models/sweatshot-background.png",
    texture_aspect_width: 1,
    texture_aspect_height: 1,
    model_url: "/models/sweatshot.glb",
    image_url: "/carousel/sweatshot-2-carousel.webp",
    description:
      "Создайте свой дизайн свитшота, используя готовые изображения или загрузите свои",
    title: "Свитшот",
    is_available: true,
    icon_url: "/icons/sparkles.svg",
  },
  {
    id: 1,
    service_name: "cup",
    uv_url: "/models/cup_background.webp",
    texture_aspect_width: 1,
    texture_aspect_height: 1,
    model_url: "/models/cup.glb",
    image_url: "/carousel/cup-carousel.webp",
    description:
      "Разнообразьте предмет обихода яркими логотипами собственного дизайна",
    title: "Кружка",
    is_available: true,
    icon_url: "/icons/coffee.svg",
  },
  {
    id: 2,
    service_name: "t-shirt",
    uv_url: "/models/t-shirt_background.webp",
    texture_aspect_width: 1,
    texture_aspect_height: 1,
    model_url: "/models/t-shirt.glb",
    image_url: "/carousel/t-shirt-w-carousel.webp",
    description: "Отличный подарок для ваших близких с собственным дизайном",
    title: "Футболка",
    is_available: false,
    icon_url: "/icons/t-shirt.svg",
  },
  {
    id: 3,
    service_name: "hoodie",
    uv_url: "/models/hoodie_background.webp",
    texture_aspect_width: 1,
    texture_aspect_height: 1,
    model_url: "/models/hoodie.glb",
    image_url: "/carousel/hoodie-carousel.webp",
    description:
      "Хотите худи с вашим логотипом? Печать DTG-методом на худи с возможностью выбора цвета",
    title: "Худи",
    is_available: false,
    icon_url: "/icons/star.svg",
  },
  {
    id: 4,
    service_name: "backback",
    uv_url: "/models/backback_background.webp",
    texture_aspect_width: 1,
    texture_aspect_height: 1,
    model_url: "/models/backback.glb",
    image_url: "/carousel/backpack-carousel.webp",
    description:
      "Рюкзак с вашим логотипом. Печать DTG-методом на худи с возможностью выбора цвета",
    title: "Рюкзак",
    is_available: false,
    icon_url: "/icons/backpack.svg",
  },
  {
    id: 5,
    service_name: "shopper",
    uv_url: "/models/shopper_background.webp",
    texture_aspect_width: 1,
    texture_aspect_height: 1,
    model_url: "/models/shopper.glb",
    image_url: "/carousel/shopper-carousel.webp",
    description: "Модный шоппер для ваших покупок. Будьте в тренде везде",
    title: "Шоппер",
    is_available: false,
    icon_url: "/icons/banknote.svg",
  },
];

const mockStockCategories: stock_categories[] = [
  { id: 0, categoryName: "white", description: "Белые логотипы" },
  { id: 1, categoryName: "grey", description: "Серые логотипы" },
];

const mockStockImages: stock_images[] = [
  {
    id: 0,
    category: 1,
    imageUrl: "/stock/grey/1.png",
    compressedImageUrl: "/stock/grey/compressed/1.webp",
    price: new Decimal(3.99),
    backgroundColor: "#ffffff",
    createdAt: new Date(),
  },
  {
    id: 1,
    category: 1,
    imageUrl: "/stock/grey/2.png",
    compressedImageUrl: "/stock/grey/compressed/2.webp",
    price: new Decimal(3.99),
    backgroundColor: "#ffffff",
    createdAt: new Date(),
  },
  {
    id: 2,
    category: 1,
    imageUrl: "/stock/grey/3.png",
    compressedImageUrl: "/stock/grey/compressed/3.webp",
    price: new Decimal(3.99),
    backgroundColor: "#ffffff",
    createdAt: new Date(),
  },
  {
    id: 3,
    category: 1,
    imageUrl: "/stock/grey/4.png",
    compressedImageUrl: "/stock/grey/compressed/4.webp",
    price: new Decimal(3.99),
    backgroundColor: "#ffffff",
    createdAt: new Date(),
  },
  {
    id: 4,
    category: 1,
    imageUrl: "/stock/grey/5.png",
    compressedImageUrl: "/stock/grey/compressed/5.webp",
    price: new Decimal(3.99),
    backgroundColor: "#ffffff",
    createdAt: new Date(),
  },
  {
    id: 5,
    category: 1,
    imageUrl: "/stock/grey/6.png",
    compressedImageUrl: "/stock/grey/compressed/6.webp",
    price: new Decimal(3.99),
    backgroundColor: "#ffffff",
    createdAt: new Date(),
  },
  {
    id: 6,
    category: 1,
    imageUrl: "/stock/grey/7.png",
    compressedImageUrl: "/stock/grey/compressed/7.webp",
    price: new Decimal(3.99),
    backgroundColor: "#ffffff",
    createdAt: new Date(),
  },
  {
    id: 7,
    category: 1,
    imageUrl: "/stock/grey/8.png",
    compressedImageUrl: "/stock/grey/compressed/8.webp",
    price: new Decimal(3.99),
    backgroundColor: "#ffffff",
    createdAt: new Date(),
  },
  {
    id: 8,
    category: 1,
    imageUrl: "/stock/grey/9.png",
    compressedImageUrl: "/stock/grey/compressed/9.webp",
    price: new Decimal(3.99),
    backgroundColor: "#ffffff",
    createdAt: new Date(),
  },
  {
    id: 9,
    category: 1,
    imageUrl: "/stock/grey/10.png",
    compressedImageUrl: "/stock/grey/compressed/10.webp",
    price: new Decimal(3.99),
    backgroundColor: "#ffffff",
    createdAt: new Date(),
  },
  {
    id: 10,
    category: 1,
    imageUrl: "/stock/grey/11.png",
    compressedImageUrl: "/stock/grey/compressed/11.webp",
    price: new Decimal(3.99),
    backgroundColor: "#ffffff",
    createdAt: new Date(),
  },
  {
    id: 11,
    category: 1,
    imageUrl: "/stock/grey/12.png",
    compressedImageUrl: "/stock/grey/compressed/12.webp",
    price: new Decimal(3.99),
    backgroundColor: "#ffffff",
    createdAt: new Date(),
  },
  {
    id: 12,
    category: 1,
    imageUrl: "/stock/grey/13.png",
    compressedImageUrl: "/stock/grey/compressed/13.webp",
    price: new Decimal(3.99),
    backgroundColor: "#ffffff",
    createdAt: new Date(),
  },
  {
    id: 13,
    category: 1,
    imageUrl: "/stock/grey/14.png",
    compressedImageUrl: "/stock/grey/compressed/14.webp",
    price: new Decimal(3.99),
    backgroundColor: "#ffffff",
    createdAt: new Date(),
  },
  {
    id: 14,
    category: 1,
    imageUrl: "/stock/grey/15.png",
    compressedImageUrl: "/stock/grey/compressed/15.webp",
    price: new Decimal(3.99),
    backgroundColor: "#ffffff",
    createdAt: new Date(),
  },
  {
    id: 15,
    category: 1,
    imageUrl: "/stock/grey/16.png",
    compressedImageUrl: "/stock/grey/compressed/16.webp",
    price: new Decimal(3.99),
    backgroundColor: "#ffffff",
    createdAt: new Date(),
  },
  {
    id: 16,
    category: 1,
    imageUrl: "/stock/grey/17.png",
    compressedImageUrl: "/stock/grey/compressed/17.webp",
    price: new Decimal(3.99),
    backgroundColor: "#ffffff",
    createdAt: new Date(),
  },
  {
    id: 17,
    category: 1,
    imageUrl: "/stock/grey/18.png",
    compressedImageUrl: "/stock/grey/compressed/18.webp",
    price: new Decimal(3.99),
    backgroundColor: "#ffffff",
    createdAt: new Date(),
  },
  {
    id: 18,
    category: 1,
    imageUrl: "/stock/grey/19.png",
    compressedImageUrl: "/stock/grey/compressed/19.webp",
    price: new Decimal(3.99),
    backgroundColor: "#ffffff",
    createdAt: new Date(),
  },
  {
    id: 19,
    category: 1,
    imageUrl: "/stock/grey/20.png",
    compressedImageUrl: "/stock/grey/compressed/20.webp",
    price: new Decimal(3.99),
    backgroundColor: "#ffffff",
    createdAt: new Date(),
  },
  {
    id: 20,
    category: 1,
    imageUrl: "/stock/grey/21.png",
    compressedImageUrl: "/stock/grey/compressed/21.webp",
    price: new Decimal(3.99),
    backgroundColor: "#ffffff",
    createdAt: new Date(),
  },
  {
    id: 21,
    category: 1,
    imageUrl: "/stock/grey/22.png",
    compressedImageUrl: "/stock/grey/compressed/22.webp",
    price: new Decimal(3.99),
    backgroundColor: "#ffffff",
    createdAt: new Date(),
  },
  {
    id: 22,
    category: 1,
    imageUrl: "/stock/grey/23.png",
    compressedImageUrl: "/stock/grey/compressed/23.webp",
    price: new Decimal(3.99),
    backgroundColor: "#ffffff",
    createdAt: new Date(),
  },
  {
    id: 23,
    category: 1,
    imageUrl: "/stock/grey/24.png",
    compressedImageUrl: "/stock/grey/compressed/24.webp",
    price: new Decimal(3.99),
    backgroundColor: "#ffffff",
    createdAt: new Date(),
  },
  {
    id: 24,
    category: 1,
    imageUrl: "/stock/grey/25.png",
    compressedImageUrl: "/stock/grey/compressed/25.webp",
    price: new Decimal(3.99),
    backgroundColor: "#ffffff",
    createdAt: new Date(),
  },
  {
    id: 25,
    category: 1,
    imageUrl: "/stock/grey/26.png",
    compressedImageUrl: "/stock/grey/compressed/26.webp",
    price: new Decimal(3.99),
    backgroundColor: "#ffffff",
    createdAt: new Date(),
  },
  {
    id: 26,
    category: 1,
    imageUrl: "/stock/grey/27.png",
    compressedImageUrl: "/stock/grey/compressed/27.webp",
    price: new Decimal(3.99),
    backgroundColor: "#ffffff",
    createdAt: new Date(),
  },
  {
    id: 27,
    category: 1,
    imageUrl: "/stock/grey/28.png",
    compressedImageUrl: "/stock/grey/compressed/28.webp",
    price: new Decimal(3.99),
    backgroundColor: "#ffffff",
    createdAt: new Date(),
  },
  {
    id: 28,
    category: 1,
    imageUrl: "/stock/grey/29.png",
    compressedImageUrl: "/stock/grey/compressed/29.webp",
    price: new Decimal(3.99),
    backgroundColor: "#ffffff",
    createdAt: new Date(),
  },
  {
    id: 29,
    category: 0,
    imageUrl: "/stock/white/30.png",
    compressedImageUrl: "/stock/white/compressed/30.webp",
    price: new Decimal(3.99),
    backgroundColor: "#03cdd7",
    createdAt: new Date(),
  },
  {
    id: 30,
    category: 0,
    imageUrl: "/stock/white/31.png",
    compressedImageUrl: "/stock/white/compressed/31.webp",
    price: new Decimal(3.99),
    backgroundColor: "#03cdd7",
    createdAt: new Date(),
  },
  {
    id: 31,
    category: 0,
    imageUrl: "/stock/white/32.png",
    compressedImageUrl: "/stock/white/compressed/32.webp",
    price: new Decimal(3.99),
    backgroundColor: "#03cdd7",
    createdAt: new Date(),
  },
  {
    id: 32,
    category: 0,
    imageUrl: "/stock/white/33.png",
    compressedImageUrl: "/stock/white/compressed/33.webp",
    price: new Decimal(3.99),
    backgroundColor: "#03cdd7",
    createdAt: new Date(),
  },
  {
    id: 33,
    category: 0,
    imageUrl: "/stock/white/34.png",
    compressedImageUrl: "/stock/white/compressed/34.webp",
    price: new Decimal(3.99),
    backgroundColor: "#03cdd7",
    createdAt: new Date(),
  },
  {
    id: 34,
    category: 0,
    imageUrl: "/stock/white/35.png",
    compressedImageUrl: "/stock/white/compressed/35.webp",
    price: new Decimal(3.99),
    backgroundColor: "#03cdd7",
    createdAt: new Date(),
  },
  {
    id: 35,
    category: 0,
    imageUrl: "/stock/white/36.png",
    compressedImageUrl: "/stock/white/compressed/36.webp",
    price: new Decimal(3.99),
    backgroundColor: "#03cdd7",
    createdAt: new Date(),
  },
  {
    id: 36,
    category: 0,
    imageUrl: "/stock/white/37.png",
    compressedImageUrl: "/stock/white/compressed/37.webp",
    price: new Decimal(3.99),
    backgroundColor: "#03cdd7",
    createdAt: new Date(),
  },
  {
    id: 37,
    category: 0,
    imageUrl: "/stock/white/38.png",
    compressedImageUrl: "/stock/white/compressed/38.webp",
    price: new Decimal(3.99),
    backgroundColor: "#03cdd7",
    createdAt: new Date(),
  },
  {
    id: 38,
    category: 0,
    imageUrl: "/stock/white/39.png",
    compressedImageUrl: "/stock/white/compressed/39.webp",
    price: new Decimal(3.99),
    backgroundColor: "#03cdd7",
    createdAt: new Date(),
  },
  {
    id: 39,
    category: 0,
    imageUrl: "/stock/white/40.png",
    compressedImageUrl: "/stock/white/compressed/40.webp",
    price: new Decimal(3.99),
    backgroundColor: "#03cdd7",
    createdAt: new Date(),
  },
  {
    id: 40,
    category: 0,
    imageUrl: "/stock/white/41.png",
    compressedImageUrl: "/stock/white/compressed/41.webp",
    price: new Decimal(3.99),
    backgroundColor: "#03cdd7",
    createdAt: new Date(),
  },
  {
    id: 41,
    category: 0,
    imageUrl: "/stock/white/42.png",
    compressedImageUrl: "/stock/white/compressed/42.webp",
    price: new Decimal(3.99),
    backgroundColor: "#03cdd7",
    createdAt: new Date(),
  },
  {
    id: 42,
    category: 0,
    imageUrl: "/stock/white/43.png",
    compressedImageUrl: "/stock/white/compressed/43.webp",
    price: new Decimal(3.99),
    backgroundColor: "#03cdd7",
    createdAt: new Date(),
  },
  {
    id: 43,
    category: 0,
    imageUrl: "/stock/white/44.png",
    compressedImageUrl: "/stock/white/compressed/44.webp",
    price: new Decimal(3.99),
    backgroundColor: "#03cdd7",
    createdAt: new Date(),
  },
  {
    id: 44,
    category: 0,
    imageUrl: "/stock/white/45.png",
    compressedImageUrl: "/stock/white/compressed/45.webp",
    price: new Decimal(3.99),
    backgroundColor: "#03cdd7",
    createdAt: new Date(),
  },
  {
    id: 45,
    category: 0,
    imageUrl: "/stock/white/46.png",
    compressedImageUrl: "/stock/white/compressed/46.webp",
    price: new Decimal(3.99),
    backgroundColor: "#03cdd7",
    createdAt: new Date(),
  },
  {
    id: 46,
    category: 0,
    imageUrl: "/stock/white/47.png",
    compressedImageUrl: "/stock/white/compressed/47.webp",
    price: new Decimal(3.99),
    backgroundColor: "#03cdd7",
    createdAt: new Date(),
  },
  {
    id: 47,
    category: 0,
    imageUrl: "/stock/white/48.png",
    compressedImageUrl: "/stock/white/compressed/48.webp",
    price: new Decimal(3.99),
    backgroundColor: "#03cdd7",
    createdAt: new Date(),
  },
  {
    id: 48,
    category: 0,
    imageUrl: "/stock/white/49.png",
    compressedImageUrl: "/stock/white/compressed/49.webp",
    price: new Decimal(3.99),
    backgroundColor: "#03cdd7",
    createdAt: new Date(),
  },
  {
    id: 49,
    category: 0,
    imageUrl: "/stock/white/50.png",
    compressedImageUrl: "/stock/white/compressed/50.webp",
    price: new Decimal(3.99),
    backgroundColor: "#03cdd7",
    createdAt: new Date(),
  },
  {
    id: 50,
    category: 0,
    imageUrl: "/stock/white/51.png",
    compressedImageUrl: "/stock/white/compressed/51.webp",
    price: new Decimal(3.99),
    backgroundColor: "#03cdd7",
    createdAt: new Date(),
  },
  {
    id: 51,
    category: 0,
    imageUrl: "/stock/white/52.png",
    compressedImageUrl: "/stock/white/compressed/52.webp",
    price: new Decimal(3.99),
    backgroundColor: "#03cdd7",
    createdAt: new Date(),
  },
  {
    id: 52,
    category: 0,
    imageUrl: "/stock/white/53.png",
    compressedImageUrl: "/stock/white/compressed/53.webp",
    price: new Decimal(3.99),
    backgroundColor: "#03cdd7",
    createdAt: new Date(),
  },
  {
    id: 53,
    category: 0,
    imageUrl: "/stock/white/54.png",
    compressedImageUrl: "/stock/white/compressed/54.webp",
    price: new Decimal(3.99),
    backgroundColor: "#03cdd7",
    createdAt: new Date(),
  },
  {
    id: 54,
    category: 0,
    imageUrl: "/stock/white/55.png",
    compressedImageUrl: "/stock/white/compressed/55.webp",
    price: new Decimal(3.99),
    backgroundColor: "#03cdd7",
    createdAt: new Date(),
  },
  {
    id: 55,
    category: 0,
    imageUrl: "/stock/white/56.png",
    compressedImageUrl: "/stock/white/compressed/56.webp",
    price: new Decimal(3.99),
    backgroundColor: "#03cdd7",
    createdAt: new Date(),
  },
  {
    id: 56,
    category: 0,
    imageUrl: "/stock/white/57.png",
    compressedImageUrl: "/stock/white/compressed/57.webp",
    price: new Decimal(3.99),
    backgroundColor: "#03cdd7",
    createdAt: new Date(),
  },
  {
    id: 57,
    category: 0,
    imageUrl: "/stock/white/58.png",
    compressedImageUrl: "/stock/white/compressed/58.webp",
    price: new Decimal(3.99),
    backgroundColor: "#03cdd7",
    createdAt: new Date(),
  },
];

async function up() {
  await prisma.services.createMany({
    data: mockServices,
  });

  await prisma.stock_categories.createMany({
    data: mockStockCategories,
  });

  await prisma.stock_images.createMany({
    data: mockStockImages,
  });
}

async function down() {
  await prisma.$executeRaw`TRUNCATE TABLE "services" CASCADE;`;
  await prisma.$executeRaw`TRUNCATE TABLE "stock_images" CASCADE;`;
  await prisma.$executeRaw`TRUNCATE TABLE "stock_categories" CASCADE;`;
}

async function main() {
  try {
    await down();
    await up();
  } catch (error) {
    console.log("Error while seeding the database", error);
  }
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.log("Fatal error", e);
    await prisma.$disconnect();
    process.exit(1);
  });
