"use client";

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/sweatshot.glb -o components/models/Sweatshot/index.tsx -r public/models --types 
*/

import * as THREE from "three";
import React, { JSX } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    handsdown_OBJ: THREE.Mesh;
  };
  materials: {
    ClothMaterial: THREE.MeshStandardMaterial;
  };
};

useGLTF.preload("/models/sweatshot.glb");

export default function Sweatshot(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/sweatshot.glb"
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        geometry={nodes.handsdown_OBJ.geometry}
        material={materials.ClothMaterial}
      />
    </group>
  );
}
